apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-application-deployment
  labels:
    app: my-application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-application
  template:
    metadata:
      labels:
        app: my-application
    spec:
      containers:
        - name: my-application-container
          image: saikiran2211/splitit-api # TODO: Update docker image
          ports:
            - containerPort: 3000
