apiVersion: v1
kind: Service
metadata:
  name: my-application-service
  annotations:
    external-dns.alpha.kubernetes.io/hostname: my-service.external-dns.my-domain.com  # TODO: Update root domain
spec:
  selector:
    app: my-application
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3000
  type: LoadBalancer